name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build test project
        run: ./gradlew test:packageLinuxX64 test:packageMacX64 test:packageWinX64
      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ matrix.os }}
          path: /lwjgl3/build
